-- Perfumes Árabes — 15 masculinos + 15 femininos (protótipo)
-- Marcas: Lattafa, Armaf, Afnan, Rasasi, Al Haramain, Maison Alhambra, Ajmal
-- Notas olfativas segundo o Fragrantica; imagens servidas pelo CDN do Fragrantica (fimgs.net).
-- Requer as colunas de supabase/migrations/add_product_details.sql e add_subcategory_column.sql.

INSERT INTO products (name, brand, description, long_description, price, stock, category, subcategory, gender, volume, concentration, fragrance_family, top_notes, heart_notes, base_notes, origin_country, show_on_home, image_url) VALUES
('Asad', 'Lattafa', 'Intenso e magnético, com pimenta preta, tabaco e baunilha.', 'Asad — "leão" em árabe — é um dos perfumes árabes mais vendidos do mundo. Abre com pimenta e ananás, evolui para um coração de café, íris e patchouli, e assenta numa base quente de baunilha, âmbar e benjoim. Uma assinatura noturna, confiante e de longa duração.', 35, 24, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Âmbar Especiado', 'Pimenta, Tabaco, Ananás', 'Patchouli, Café, Íris', 'Baunilha, Âmbar, Madeira Seca, Benjoim, Ládano', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.72821.jpg'),
('Asad Zanzibar', 'Lattafa', 'A versão solar do Asad, com água de coco, sal e lavanda.', 'Inspirado na ilha de Zanzibar, este flanker leva o ADN do Asad para o verão: lavanda e pimenta na abertura, um coração salino de água de coco e íris, e um fundo cremoso de baunilha e incenso. Fresco, sensual e muito versátil.', 39, 18, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Aromático Aquático', 'Lavanda, Pimenta', 'Água de Coco, Íris, Sal', 'Baunilha, Incenso', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.90713.jpg'),
('Fakhar Black', 'Lattafa', 'Elegante e fresco, com maçã, gengibre e lavanda.', 'Fakhar Black é um fougère moderno e polido: maçã, bergamota e gengibre na saída, um coração aromático de lavanda, salva e zimbro, e uma base de fava tonka, cedro e vetiver. Ideal para o escritório e para o dia a dia.', 32, 30, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Aromático Fougère', 'Maçã, Bergamota, Gengibre', 'Lavanda, Salva, Bagas de Zimbro, Gerânio', 'Fava Tonka, Cedro, Madeira de Âmbar, Vetiver', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.70465.jpg'),
('Odyssey Homme', 'Armaf', 'Cardamomo, flor de laranjeira e baunilha num frasco icónico.', 'Odyssey Homme combina a frescura do néroli e da tangerina com o calor do cardamomo. O coração de flor de laranjeira e rosa dá lugar a uma base suave de baunilha, sândalo e âmbar. Sofisticado e fácil de usar.', 35, 15, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Âmbar Floral', 'Cardamomo, Néroli, Tangerina', 'Flor de Laranjeira, Rosa', 'Baunilha, Notas Amadeiradas, Âmbar, Sândalo', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.64464.jpg'),
('Club de Nuit Intense Man', 'Armaf', 'O clássico de culto: ananás, bétula fumada e almíscar.', 'Um dos perfumes árabes mais célebres de sempre. Abre com limão, ananás, groselha preta e maçã, passa por um coração fumado de bétula, jasmim e rosa, e termina em almíscar, âmbar cinzento, patchouli e baunilha. Projeção e fixação excecionais.', 49, 26, 'perfumes', 'Masculino', 'Masculino', '105ml', 'Eau de Toilette', 'Chipre Frutado', 'Limão, Ananás, Bergamota, Groselha Preta, Maçã', 'Bétula, Jasmim, Rosa', 'Almíscar, Âmbar Cinzento, Patchouli, Baunilha', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.34696.jpg'),
('Club de Nuit Blue Iconic', 'Armaf', 'Fresco e vibrante, com toranja, gengibre e incenso.', 'Club de Nuit Blue Iconic é uma fragrância azul, limpa e enérgica: toranja, limão e hortelã na saída, gengibre, melão e noz-moscada no coração, e uma base amadeirada de incenso, sândalo e cedro.', 45, 20, 'perfumes', 'Masculino', 'Masculino', '105ml', 'Eau de Parfum', 'Amadeirado Aromático', 'Toranja, Limão, Hortelã, Pimenta Rosa, Coentros', 'Gengibre, Melão, Jasmim, Noz-moscada', 'Notas Amadeiradas, Incenso, Sândalo, Âmbar, Cedro, Patchouli, Ládano', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.78475.jpg'),
('9pm', 'Afnan', 'Doce e sedutor, com maçã, canela e baunilha.', '9pm foi criado para a noite: maçã, canela, lavanda e bergamota na abertura, um coração de flor de laranjeira e lírio-do-vale, e uma base envolvente de baunilha, fava tonka, âmbar e patchouli. Um sucesso viral para encontros e saídas.', 42, 22, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Âmbar Baunilhado', 'Maçã, Canela, Lavanda, Bergamota', 'Flor de Laranjeira, Lírio-do-vale', 'Baunilha, Fava Tonka, Âmbar, Patchouli', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.65414.jpg'),
('Supremacy Not Only Intense', 'Afnan', 'Extrait potente com groselha preta, musgo de carvalho e açafrão.', 'Supremacy Not Only Intense é a versão mais concentrada da linha: groselha preta, bergamota e maçã, coração de musgo de carvalho, patchouli e lavanda, e base de âmbar cinzento, almíscar e açafrão. Elegante, fumado e muito duradouro.', 55, 12, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Extrait de Parfum', 'Chipre Frutado', 'Groselha Preta, Bergamota, Maçã', 'Musgo de Carvalho, Patchouli, Lavanda', 'Âmbar Cinzento, Almíscar, Açafrão', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.68271.jpg'),
('Turathi Blue', 'Afnan', 'Citrinos luminosos sobre madeiras e âmbar.', 'Turathi Blue celebra a herança árabe com um toque moderno: citrinos vibrantes, um coração de notas amadeiradas e âmbar, e uma base de almíscar, especiarias e patchouli. Frasco de design marcante e rasto fresco.', 45, 16, 'perfumes', 'Masculino', 'Masculino', '90ml', 'Eau de Parfum', 'Amadeirado Especiado', 'Citrinos', 'Notas Amadeiradas, Âmbar', 'Almíscar, Notas Especiadas, Patchouli', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.70839.jpg'),
('Hawas for Him', 'Rasasi', 'O aquático mais desejado: maçã, ameixa e âmbar cinzento.', 'Hawas for Him é uma referência dos perfumes frescos de verão. Maçã, bergamota, limão e canela na saída, um coração aquático de ameixa, flor de laranjeira e cardamomo, e uma base de âmbar cinzento, almíscar e madeira flutuante.', 59, 20, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Aromático Aquático', 'Maçã, Bergamota, Limão, Canela', 'Notas Aquáticas, Ameixa, Flor de Laranjeira, Cardamomo', 'Âmbar Cinzento, Almíscar, Patchouli, Madeira Flutuante', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.46890.jpg'),
('Hawas Ice', 'Rasasi', 'Ainda mais gelado: maçã, anis-estrelado e musgo de carvalho.', 'Hawas Ice intensifica a frescura do original: maçã, limão, bergamota e anis-estrelado, coração de ameixa, flor de laranjeira e cardamomo, e um fundo de almíscar, âmbar, madeira flutuante e musgo de carvalho.', 62, 14, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Aromático Aquático', 'Maçã, Limão, Bergamota, Anis-estrelado', 'Ameixa, Flor de Laranjeira, Cardamomo', 'Almíscar, Âmbar, Madeira Flutuante, Musgo de Carvalho', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.89050.jpg'),
('L''Aventure', 'Al Haramain', 'Citrino e amadeirado, com limão, elemi e almíscar.', 'L''Aventure é uma fragrância cítrica e amadeirada de grande projeção: limão, bergamota e elemi na saída, coração de madeiras, jasmim e lírio-do-vale, e base de almíscar, patchouli e âmbar.', 38, 22, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Chipre Frutado', 'Limão, Bergamota, Elemi', 'Notas Amadeiradas, Jasmim, Lírio-do-vale', 'Almíscar, Patchouli, Âmbar', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.40405.jpg'),
('Salvo', 'Maison Alhambra', 'Bergamota, pimenta de Sichuan e ambroxan.', 'Salvo é fresco, especiado e moderno: bergamota luminosa, um coração de lavanda, pimenta de Sichuan, anis-estrelado e noz-moscada, e uma base de ambroxan e baunilha. Excelente relação qualidade-preço.', 29, 28, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Aromático Especiado', 'Bergamota', 'Lavanda, Pimenta de Sichuan, Anis-estrelado, Noz-moscada', 'Ambroxan, Baunilha', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.93538.jpg'),
('Jean Lowe Immortal', 'Maison Alhambra', 'Gengibre, alecrim e ambroxan num perfil limpo e moderno.', 'Jean Lowe Immortal combina gengibre, toranja e bergamota com um coração aromático de alecrim, salva e gerânio. A base de ambroxan, âmbar e ládano dá-lhe um rasto mineral e elegante.', 29, 25, 'perfumes', 'Masculino', 'Masculino', '100ml', 'Eau de Parfum', 'Amadeirado Aromático', 'Gengibre, Toranja, Bergamota', 'Alecrim, Notas Aquáticas, Salva, Gerânio', 'Ambroxan, Âmbar, Ládano', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.83666.jpg'),
('Evoke for Him', 'Ajmal', 'Lavanda, cardamomo e sândalo para um estilo clássico.', 'Evoke for Him é a proposta clássica da Ajmal: lavanda, maçã e bergamota, um coração de cardamomo, heliotrópio, raiz de íris e zimbro, e uma base de sândalo, vetiver e almíscar.', 52, 12, 'perfumes', 'Masculino', 'Masculino', '90ml', 'Eau de Parfum', 'Amadeirado Aromático', 'Lavanda, Maçã, Bergamota', 'Cardamomo, Heliotrópio, Raiz de Íris, Zimbro', 'Sândalo, Vetiver, Almíscar', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.32527.jpg'),
('Yara', 'Lattafa', 'O fenómeno cor-de-rosa: orquídea, frutos tropicais e baunilha.', 'Yara é um dos perfumes árabes mais vendidos e virais do mundo. Abre com orquídea, heliotrópio e tangerina, revela um coração gourmand de frutos tropicais e termina numa base cremosa de baunilha, almíscar e sândalo. Doce, macio e irresistível.', 32, 30, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Âmbar Baunilhado', 'Orquídea, Heliotrópio, Tangerina', 'Acorde Gourmand, Frutos Tropicais', 'Baunilha, Almíscar, Sândalo', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.76880.jpg'),
('Yara Moi', 'Lattafa', 'Jasmim, pêssego e caramelo — a versão mais elegante do Yara.', 'Yara Moi traz um lado mais sofisticado à família Yara: jasmim e pêssego na saída, um coração de caramelo e âmbar, e uma base de patchouli e sândalo. Feminino, quente e envolvente.', 34, 22, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Âmbar Floral', 'Jasmim, Pêssego', 'Caramelo, Âmbar', 'Patchouli, Sândalo', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.80722.jpg'),
('Yara Candy', 'Lattafa', 'Divertido e doce, com rebuçado de morango e gardénia.', 'Yara Candy é a novidade mais doce da coleção: groselha preta e tangerina verde, um coração de rebuçado de morango e gardénia, e uma base de baunilha, almíscar, âmbar e sândalo.', 36, 20, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado Gourmand', 'Groselha Preta, Tangerina Verde', 'Rebuçado de Morango, Gardénia', 'Baunilha, Almíscar, Âmbar, Sândalo', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.95752.jpg'),
('Yara Tous', 'Lattafa', 'Tropical e solar, com manga, coco e maracujá.', 'Yara Tous leva-nos para uma praia tropical: manga, coco e maracujá na saída, um coração floral de jasmim, flor de laranjeira e heliotrópio, e um fundo de baunilha, almíscar e cashmeran.', 34, 18, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado', 'Manga, Coco, Maracujá', 'Jasmim, Flor de Laranjeira, Heliotrópio', 'Baunilha, Almíscar, Cashmeran', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.83320.jpg'),
('Haya', 'Lattafa', 'Festivo e luminoso, com champanhe, morango e gardénia.', 'Haya é pura celebração: champanhe, morango, tangerina, laranja sanguínea e rosa na abertura, coração de gardénia, jasmim e orquídea, e base de âmbar, sândalo e castanha.', 35, 16, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado', 'Champanhe, Morango, Tangerina, Laranja Sanguínea, Rosa', 'Gardénia, Jasmim, Orquídea', 'Âmbar, Sândalo, Castanha', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.85031.jpg'),
('Mayar', 'Lattafa', 'Delicado e fresco, com líchia, framboesa e peónia.', 'Mayar é leve e feminino: líchia, framboesa e folha de violeta na saída, um bouquet de rosa, peónia e jasmim, e uma base suave de almíscar e baunilha. Perfeito para o dia a dia.', 36, 20, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado', 'Líchia, Framboesa, Folha de Violeta', 'Rosa, Peónia, Jasmim', 'Almíscar, Baunilha', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.84309.jpg'),
('Sakeena', 'Lattafa', 'Maracujá, framboesa e praliné num perfil gourmand.', 'Sakeena combina frescura e doçura: maracujá, notas ozónicas e tangerina, um coração de framboesa, rosa, flor de laranjeira e sal, e uma base viciante de toffee, praliné, baunilha e almíscar.', 38, 14, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Âmbar Floral', 'Maracujá, Notas Ozónicas, Tangerina', 'Framboesa, Rosa, Flor de Laranjeira, Sal', 'Toffee, Praliné, Baunilha, Almíscar', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.85094.jpg'),
('Fakhar Rose', 'Lattafa', 'Bouquet de flores brancas com tuberosa, jasmim e baunilha.', 'Fakhar Rose é um floral branco rico e luminoso: notas frutadas, lírio, romã e aldeídos, um coração de tuberosa, jasmim, gardénia, ylang-ylang e rosa, e uma base de baunilha, almíscar, sândalo e ambroxan.', 32, 26, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Branco', 'Notas Frutadas, Lírio, Romã, Aldeídos', 'Tuberosa, Jasmim, Gardénia, Ylang-Ylang, Rosa, Madressilva, Peónia', 'Baunilha, Almíscar, Sândalo, Ambroxan', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.70466.jpg'),
('Qimmah for Women', 'Lattafa', 'Amêndoa, café e cacau num gourmand sedutor.', 'Qimmah for Women é um gourmand noturno: amêndoa e café na saída, um coração de jasmim, tuberosa e fava tonka, e uma base de baunilha, cacau e sândalo.', 39, 12, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Âmbar Baunilhado', 'Amêndoa, Café', 'Jasmim, Tuberosa, Fava Tonka', 'Baunilha, Cacau, Sândalo', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.82793.jpg'),
('Club de Nuit Woman', 'Armaf', 'Chipre elegante com rosa, líchia e patchouli.', 'Club de Nuit Woman é a contraparte feminina do icónico Club de Nuit: laranja, bergamota, toranja e pêssego, um coração de rosa, jasmim, gerânio e líchia, e uma base de patchouli, almíscar, baunilha e vetiver.', 42, 18, 'perfumes', 'Feminino', 'Feminino', '105ml', 'Eau de Parfum', 'Chipre Floral', 'Laranja, Bergamota, Toranja, Pêssego', 'Rosa, Jasmim, Gerânio, Líchia', 'Patchouli, Almíscar, Baunilha, Vetiver', 'Emirados Árabes Unidos', true, 'https://fimgs.net/mdimg/perfume/375x500.27655.jpg'),
('9pm pour Femme', 'Afnan', 'Framboesa, peónia e cedro para noites especiais.', '9pm pour Femme é a versão feminina do best-seller da Afnan: framboesa, violeta, maçã e laranja, um coração de rosa, peónia, íris e jasmim, e uma base amadeirada de cipreste, pinheiro, cedro e âmbar.', 42, 15, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado', 'Framboesa, Violeta, Maçã, Laranja', 'Rosa, Peónia, Íris, Jasmim', 'Cipreste, Pinheiro, Cedro, Âmbar', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.78544.jpg'),
('Hawas for Her', 'Rasasi', 'Romã, íris e praliné num frasco de luxo.', 'Hawas for Her é frutado e sofisticado: romã, maçã e toranja na saída, um coração de íris, jasmim e citrinos, e uma base de praliné, patchouli e vetiver.', 59, 14, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado', 'Romã, Maçã, Toranja', 'Íris, Jasmim, Citrinos', 'Praliné, Patchouli, Vetiver', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.67146.jpg'),
('Delilah', 'Maison Alhambra', 'Ruibarbo, líchia e rosa num perfil delicado.', 'Delilah é romântico e luminoso: ruibarbo, líchia e bergamota na abertura, um bouquet de rosa, peónia e lírio, e uma base de almíscar, cashmeran e baunilha.', 29, 24, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Floral Frutado', 'Ruibarbo, Líchia, Bergamota', 'Rosa, Peónia, Lírio', 'Almíscar, Cashmeran, Baunilha', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.90273.jpg'),
('L''Aventure Femme', 'Al Haramain', 'Ananás, groselha preta e frésia com fundo de baunilha.', 'L''Aventure Femme é frutado e confiante: ananás, groselha preta, bergamota e frutos silvestres, um coração de cedro, frésia e rosa, e uma base de almíscar, sândalo, âmbar e baunilha.', 38, 16, 'perfumes', 'Feminino', 'Feminino', '100ml', 'Eau de Parfum', 'Chipre Frutado', 'Ananás, Groselha Preta, Bergamota, Frutos Silvestres', 'Cedro, Frésia, Rosa', 'Almíscar, Sândalo, Âmbar, Baunilha', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.51820.jpg'),
('Evoke for Her', 'Ajmal', 'Pimenta rosa, rosa e íris com fundo de patchouli.', 'Evoke for Her é um chipre floral moderno: pimenta rosa e bergamota na saída, um coração de rosa, raiz de íris e jasmim, e uma base de patchouli, musgo de carvalho e baunilha.', 52, 10, 'perfumes', 'Feminino', 'Feminino', '75ml', 'Eau de Parfum', 'Chipre Floral', 'Pimenta Rosa, Bergamota', 'Rosa, Raiz de Íris, Jasmim', 'Patchouli, Musgo de Carvalho, Baunilha', 'Emirados Árabes Unidos', false, 'https://fimgs.net/mdimg/perfume/375x500.32526.jpg');
