import { Product } from "@/types/shop";

// Catálogo local (protótipo): as páginas públicas leem daqui em vez do Supabase.
// Gerado a partir de supabase/seed_perfumes_arabes.sql, com os mesmos ids da base de dados.
export const LOCAL_PRODUCTS: Product[] = [
    {
        "id": "6a66ec17-53f4-4b27-9d2a-87e4822d1ab1",
        "name": "Asad",
        "brand": "Lattafa",
        "description": "Intenso e magnético, com pimenta preta, tabaco e baunilha.",
        "long_description": "Asad — \"leão\" em árabe — é um dos perfumes árabes mais vendidos do mundo. Abre com pimenta e ananás, evolui para um coração de café, íris e patchouli, e assenta numa base quente de baunilha, âmbar e benjoim. Uma assinatura noturna, confiante e de longa duração.",
        "price": 35,
        "stock": 24,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Especiado",
        "top_notes": "Pimenta, Tabaco, Ananás",
        "heart_notes": "Patchouli, Café, Íris",
        "base_notes": "Baunilha, Âmbar, Madeira Seca, Benjoim, Ládano",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.72821.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "f3020d8b-cab4-4f66-a6e9-cef360bbb97a",
        "name": "Asad Zanzibar",
        "brand": "Lattafa",
        "description": "A versão solar do Asad, com água de coco, sal e lavanda.",
        "long_description": "Inspirado na ilha de Zanzibar, este flanker leva o ADN do Asad para o verão: lavanda e pimenta na abertura, um coração salino de água de coco e íris, e um fundo cremoso de baunilha e incenso. Fresco, sensual e muito versátil.",
        "price": 39,
        "stock": 18,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Aromático Aquático",
        "top_notes": "Lavanda, Pimenta",
        "heart_notes": "Água de Coco, Íris, Sal",
        "base_notes": "Baunilha, Incenso",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.90713.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "a8c28974-d88e-4563-ac36-2255e57339c8",
        "name": "Fakhar Black",
        "brand": "Lattafa",
        "description": "Elegante e fresco, com maçã, gengibre e lavanda.",
        "long_description": "Fakhar Black é um fougère moderno e polido: maçã, bergamota e gengibre na saída, um coração aromático de lavanda, salva e zimbro, e uma base de fava tonka, cedro e vetiver. Ideal para o escritório e para o dia a dia.",
        "price": 32,
        "stock": 30,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Aromático Fougère",
        "top_notes": "Maçã, Bergamota, Gengibre",
        "heart_notes": "Lavanda, Salva, Bagas de Zimbro, Gerânio",
        "base_notes": "Fava Tonka, Cedro, Madeira de Âmbar, Vetiver",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.70465.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "63f6c9d2-b040-4893-8fc0-e300d16c0465",
        "name": "Odyssey Homme",
        "brand": "Armaf",
        "description": "Cardamomo, flor de laranjeira e baunilha num frasco icónico.",
        "long_description": "Odyssey Homme combina a frescura do néroli e da tangerina com o calor do cardamomo. O coração de flor de laranjeira e rosa dá lugar a uma base suave de baunilha, sândalo e âmbar. Sofisticado e fácil de usar.",
        "price": 35,
        "stock": 15,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Floral",
        "top_notes": "Cardamomo, Néroli, Tangerina",
        "heart_notes": "Flor de Laranjeira, Rosa",
        "base_notes": "Baunilha, Notas Amadeiradas, Âmbar, Sândalo",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.64464.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "1c8d65ef-6aa7-4657-a6b1-54bc61d22c3a",
        "name": "Club de Nuit Intense Man",
        "brand": "Armaf",
        "description": "O clássico de culto: ananás, bétula fumada e almíscar.",
        "long_description": "Um dos perfumes árabes mais célebres de sempre. Abre com limão, ananás, groselha preta e maçã, passa por um coração fumado de bétula, jasmim e rosa, e termina em almíscar, âmbar cinzento, patchouli e baunilha. Projeção e fixação excecionais.",
        "price": 49,
        "stock": 26,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "105ml",
        "concentration": "Eau de Toilette",
        "fragrance_family": "Chipre Frutado",
        "top_notes": "Limão, Ananás, Bergamota, Groselha Preta, Maçã",
        "heart_notes": "Bétula, Jasmim, Rosa",
        "base_notes": "Almíscar, Âmbar Cinzento, Patchouli, Baunilha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.34696.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "f9566db2-1e75-4a0a-9f49-fd7699963e27",
        "name": "Club de Nuit Blue Iconic",
        "brand": "Armaf",
        "description": "Fresco e vibrante, com toranja, gengibre e incenso.",
        "long_description": "Club de Nuit Blue Iconic é uma fragrância azul, limpa e enérgica: toranja, limão e hortelã na saída, gengibre, melão e noz-moscada no coração, e uma base amadeirada de incenso, sândalo e cedro.",
        "price": 45,
        "stock": 20,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "105ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Amadeirado Aromático",
        "top_notes": "Toranja, Limão, Hortelã, Pimenta Rosa, Coentros",
        "heart_notes": "Gengibre, Melão, Jasmim, Noz-moscada",
        "base_notes": "Notas Amadeiradas, Incenso, Sândalo, Âmbar, Cedro, Patchouli, Ládano",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.78475.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "3ad96dd6-8bbf-4194-b8ef-679b56e37a07",
        "name": "9pm",
        "brand": "Afnan",
        "description": "Doce e sedutor, com maçã, canela e baunilha.",
        "long_description": "9pm foi criado para a noite: maçã, canela, lavanda e bergamota na abertura, um coração de flor de laranjeira e lírio-do-vale, e uma base envolvente de baunilha, fava tonka, âmbar e patchouli. Um sucesso viral para encontros e saídas.",
        "price": 42,
        "stock": 22,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Baunilhado",
        "top_notes": "Maçã, Canela, Lavanda, Bergamota",
        "heart_notes": "Flor de Laranjeira, Lírio-do-vale",
        "base_notes": "Baunilha, Fava Tonka, Âmbar, Patchouli",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.65414.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "38f03312-51af-4011-b62a-da229462161a",
        "name": "Supremacy Not Only Intense",
        "brand": "Afnan",
        "description": "Extrait potente com groselha preta, musgo de carvalho e açafrão.",
        "long_description": "Supremacy Not Only Intense é a versão mais concentrada da linha: groselha preta, bergamota e maçã, coração de musgo de carvalho, patchouli e lavanda, e base de âmbar cinzento, almíscar e açafrão. Elegante, fumado e muito duradouro.",
        "price": 55,
        "stock": 12,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Extrait de Parfum",
        "fragrance_family": "Chipre Frutado",
        "top_notes": "Groselha Preta, Bergamota, Maçã",
        "heart_notes": "Musgo de Carvalho, Patchouli, Lavanda",
        "base_notes": "Âmbar Cinzento, Almíscar, Açafrão",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.68271.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "d927d019-69d1-478a-bb58-70c005ae67f8",
        "name": "Turathi Blue",
        "brand": "Afnan",
        "description": "Citrinos luminosos sobre madeiras e âmbar.",
        "long_description": "Turathi Blue celebra a herança árabe com um toque moderno: citrinos vibrantes, um coração de notas amadeiradas e âmbar, e uma base de almíscar, especiarias e patchouli. Frasco de design marcante e rasto fresco.",
        "price": 45,
        "stock": 16,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "90ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Amadeirado Especiado",
        "top_notes": "Citrinos",
        "heart_notes": "Notas Amadeiradas, Âmbar",
        "base_notes": "Almíscar, Notas Especiadas, Patchouli",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.70839.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "eeef2200-74c6-4831-a5b1-0fce02e99d27",
        "name": "Hawas for Him",
        "brand": "Rasasi",
        "description": "O aquático mais desejado: maçã, ameixa e âmbar cinzento.",
        "long_description": "Hawas for Him é uma referência dos perfumes frescos de verão. Maçã, bergamota, limão e canela na saída, um coração aquático de ameixa, flor de laranjeira e cardamomo, e uma base de âmbar cinzento, almíscar e madeira flutuante.",
        "price": 59,
        "stock": 20,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Aromático Aquático",
        "top_notes": "Maçã, Bergamota, Limão, Canela",
        "heart_notes": "Notas Aquáticas, Ameixa, Flor de Laranjeira, Cardamomo",
        "base_notes": "Âmbar Cinzento, Almíscar, Patchouli, Madeira Flutuante",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.46890.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "65826049-e4ac-4f60-b7e1-a26c4f1d9fad",
        "name": "Hawas Ice",
        "brand": "Rasasi",
        "description": "Ainda mais gelado: maçã, anis-estrelado e musgo de carvalho.",
        "long_description": "Hawas Ice intensifica a frescura do original: maçã, limão, bergamota e anis-estrelado, coração de ameixa, flor de laranjeira e cardamomo, e um fundo de almíscar, âmbar, madeira flutuante e musgo de carvalho.",
        "price": 62,
        "stock": 14,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Aromático Aquático",
        "top_notes": "Maçã, Limão, Bergamota, Anis-estrelado",
        "heart_notes": "Ameixa, Flor de Laranjeira, Cardamomo",
        "base_notes": "Almíscar, Âmbar, Madeira Flutuante, Musgo de Carvalho",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.89050.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "76a1d91f-ed98-4667-8dee-412ba442174d",
        "name": "L'Aventure",
        "brand": "Al Haramain",
        "description": "Citrino e amadeirado, com limão, elemi e almíscar.",
        "long_description": "L'Aventure é uma fragrância cítrica e amadeirada de grande projeção: limão, bergamota e elemi na saída, coração de madeiras, jasmim e lírio-do-vale, e base de almíscar, patchouli e âmbar.",
        "price": 38,
        "stock": 22,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Chipre Frutado",
        "top_notes": "Limão, Bergamota, Elemi",
        "heart_notes": "Notas Amadeiradas, Jasmim, Lírio-do-vale",
        "base_notes": "Almíscar, Patchouli, Âmbar",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.40405.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "d22bd32f-610b-4806-8fbe-e3c7f1fd8f3e",
        "name": "Salvo",
        "brand": "Maison Alhambra",
        "description": "Bergamota, pimenta de Sichuan e ambroxan.",
        "long_description": "Salvo é fresco, especiado e moderno: bergamota luminosa, um coração de lavanda, pimenta de Sichuan, anis-estrelado e noz-moscada, e uma base de ambroxan e baunilha. Excelente relação qualidade-preço.",
        "price": 29,
        "stock": 28,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Aromático Especiado",
        "top_notes": "Bergamota",
        "heart_notes": "Lavanda, Pimenta de Sichuan, Anis-estrelado, Noz-moscada",
        "base_notes": "Ambroxan, Baunilha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.93538.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "7a6c2210-75d0-44e0-8fc8-419db651d199",
        "name": "Jean Lowe Immortal",
        "brand": "Maison Alhambra",
        "description": "Gengibre, alecrim e ambroxan num perfil limpo e moderno.",
        "long_description": "Jean Lowe Immortal combina gengibre, toranja e bergamota com um coração aromático de alecrim, salva e gerânio. A base de ambroxan, âmbar e ládano dá-lhe um rasto mineral e elegante.",
        "price": 29,
        "stock": 25,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Amadeirado Aromático",
        "top_notes": "Gengibre, Toranja, Bergamota",
        "heart_notes": "Alecrim, Notas Aquáticas, Salva, Gerânio",
        "base_notes": "Ambroxan, Âmbar, Ládano",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.83666.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "6ae30931-b5f2-454f-8e2f-95653c2547db",
        "name": "Evoke for Him",
        "brand": "Ajmal",
        "description": "Lavanda, cardamomo e sândalo para um estilo clássico.",
        "long_description": "Evoke for Him é a proposta clássica da Ajmal: lavanda, maçã e bergamota, um coração de cardamomo, heliotrópio, raiz de íris e zimbro, e uma base de sândalo, vetiver e almíscar.",
        "price": 52,
        "stock": 12,
        "category": "perfumes",
        "subcategory": "Masculino",
        "gender": "Masculino",
        "volume": "90ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Amadeirado Aromático",
        "top_notes": "Lavanda, Maçã, Bergamota",
        "heart_notes": "Cardamomo, Heliotrópio, Raiz de Íris, Zimbro",
        "base_notes": "Sândalo, Vetiver, Almíscar",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.32527.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "7a3014cb-9285-4a3f-a5a0-69debedc8859",
        "name": "Yara",
        "brand": "Lattafa",
        "description": "O fenómeno cor-de-rosa: orquídea, frutos tropicais e baunilha.",
        "long_description": "Yara é um dos perfumes árabes mais vendidos e virais do mundo. Abre com orquídea, heliotrópio e tangerina, revela um coração gourmand de frutos tropicais e termina numa base cremosa de baunilha, almíscar e sândalo. Doce, macio e irresistível.",
        "price": 32,
        "stock": 30,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Baunilhado",
        "top_notes": "Orquídea, Heliotrópio, Tangerina",
        "heart_notes": "Acorde Gourmand, Frutos Tropicais",
        "base_notes": "Baunilha, Almíscar, Sândalo",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.76880.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "34ecec10-0066-477a-87f7-1b18a086a46f",
        "name": "Yara Moi",
        "brand": "Lattafa",
        "description": "Jasmim, pêssego e caramelo — a versão mais elegante do Yara.",
        "long_description": "Yara Moi traz um lado mais sofisticado à família Yara: jasmim e pêssego na saída, um coração de caramelo e âmbar, e uma base de patchouli e sândalo. Feminino, quente e envolvente.",
        "price": 34,
        "stock": 22,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Floral",
        "top_notes": "Jasmim, Pêssego",
        "heart_notes": "Caramelo, Âmbar",
        "base_notes": "Patchouli, Sândalo",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.80722.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "9c758471-b424-4bad-8897-366e5937b8f5",
        "name": "Yara Candy",
        "brand": "Lattafa",
        "description": "Divertido e doce, com rebuçado de morango e gardénia.",
        "long_description": "Yara Candy é a novidade mais doce da coleção: groselha preta e tangerina verde, um coração de rebuçado de morango e gardénia, e uma base de baunilha, almíscar, âmbar e sândalo.",
        "price": 36,
        "stock": 20,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado Gourmand",
        "top_notes": "Groselha Preta, Tangerina Verde",
        "heart_notes": "Rebuçado de Morango, Gardénia",
        "base_notes": "Baunilha, Almíscar, Âmbar, Sândalo",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.95752.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "86abfdf3-5612-4c0a-b1c0-79fbefc0f21d",
        "name": "Yara Tous",
        "brand": "Lattafa",
        "description": "Tropical e solar, com manga, coco e maracujá.",
        "long_description": "Yara Tous leva-nos para uma praia tropical: manga, coco e maracujá na saída, um coração floral de jasmim, flor de laranjeira e heliotrópio, e um fundo de baunilha, almíscar e cashmeran.",
        "price": 34,
        "stock": 18,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado",
        "top_notes": "Manga, Coco, Maracujá",
        "heart_notes": "Jasmim, Flor de Laranjeira, Heliotrópio",
        "base_notes": "Baunilha, Almíscar, Cashmeran",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.83320.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "2dd91aaa-9850-4921-bd05-27d857d79393",
        "name": "Haya",
        "brand": "Lattafa",
        "description": "Festivo e luminoso, com champanhe, morango e gardénia.",
        "long_description": "Haya é pura celebração: champanhe, morango, tangerina, laranja sanguínea e rosa na abertura, coração de gardénia, jasmim e orquídea, e base de âmbar, sândalo e castanha.",
        "price": 35,
        "stock": 16,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado",
        "top_notes": "Champanhe, Morango, Tangerina, Laranja Sanguínea, Rosa",
        "heart_notes": "Gardénia, Jasmim, Orquídea",
        "base_notes": "Âmbar, Sândalo, Castanha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.85031.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "147374a4-6d99-4a94-a31b-e0ba38986bea",
        "name": "Mayar",
        "brand": "Lattafa",
        "description": "Delicado e fresco, com líchia, framboesa e peónia.",
        "long_description": "Mayar é leve e feminino: líchia, framboesa e folha de violeta na saída, um bouquet de rosa, peónia e jasmim, e uma base suave de almíscar e baunilha. Perfeito para o dia a dia.",
        "price": 36,
        "stock": 20,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado",
        "top_notes": "Líchia, Framboesa, Folha de Violeta",
        "heart_notes": "Rosa, Peónia, Jasmim",
        "base_notes": "Almíscar, Baunilha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.84309.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "e133210c-640c-4dce-b11f-d484b649683f",
        "name": "Sakeena",
        "brand": "Lattafa",
        "description": "Maracujá, framboesa e praliné num perfil gourmand.",
        "long_description": "Sakeena combina frescura e doçura: maracujá, notas ozónicas e tangerina, um coração de framboesa, rosa, flor de laranjeira e sal, e uma base viciante de toffee, praliné, baunilha e almíscar.",
        "price": 38,
        "stock": 14,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Floral",
        "top_notes": "Maracujá, Notas Ozónicas, Tangerina",
        "heart_notes": "Framboesa, Rosa, Flor de Laranjeira, Sal",
        "base_notes": "Toffee, Praliné, Baunilha, Almíscar",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.85094.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "cc56530d-7fcb-4763-88bf-9114aa100202",
        "name": "Fakhar Rose",
        "brand": "Lattafa",
        "description": "Bouquet de flores brancas com tuberosa, jasmim e baunilha.",
        "long_description": "Fakhar Rose é um floral branco rico e luminoso: notas frutadas, lírio, romã e aldeídos, um coração de tuberosa, jasmim, gardénia, ylang-ylang e rosa, e uma base de baunilha, almíscar, sândalo e ambroxan.",
        "price": 32,
        "stock": 26,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Branco",
        "top_notes": "Notas Frutadas, Lírio, Romã, Aldeídos",
        "heart_notes": "Tuberosa, Jasmim, Gardénia, Ylang-Ylang, Rosa, Madressilva, Peónia",
        "base_notes": "Baunilha, Almíscar, Sândalo, Ambroxan",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.70466.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "402d2a05-834c-45f5-b55b-54b06811768a",
        "name": "Qimmah for Women",
        "brand": "Lattafa",
        "description": "Amêndoa, café e cacau num gourmand sedutor.",
        "long_description": "Qimmah for Women é um gourmand noturno: amêndoa e café na saída, um coração de jasmim, tuberosa e fava tonka, e uma base de baunilha, cacau e sândalo.",
        "price": 39,
        "stock": 12,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Âmbar Baunilhado",
        "top_notes": "Amêndoa, Café",
        "heart_notes": "Jasmim, Tuberosa, Fava Tonka",
        "base_notes": "Baunilha, Cacau, Sândalo",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.82793.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "abf72bf1-4b3f-40ae-9cf7-8a38bc466f8e",
        "name": "Club de Nuit Woman",
        "brand": "Armaf",
        "description": "Chipre elegante com rosa, líchia e patchouli.",
        "long_description": "Club de Nuit Woman é a contraparte feminina do icónico Club de Nuit: laranja, bergamota, toranja e pêssego, um coração de rosa, jasmim, gerânio e líchia, e uma base de patchouli, almíscar, baunilha e vetiver.",
        "price": 42,
        "stock": 18,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "105ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Chipre Floral",
        "top_notes": "Laranja, Bergamota, Toranja, Pêssego",
        "heart_notes": "Rosa, Jasmim, Gerânio, Líchia",
        "base_notes": "Patchouli, Almíscar, Baunilha, Vetiver",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": true,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.27655.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "bdb7a136-29eb-48c6-9805-ca4b884fb7dc",
        "name": "9pm pour Femme",
        "brand": "Afnan",
        "description": "Framboesa, peónia e cedro para noites especiais.",
        "long_description": "9pm pour Femme é a versão feminina do best-seller da Afnan: framboesa, violeta, maçã e laranja, um coração de rosa, peónia, íris e jasmim, e uma base amadeirada de cipreste, pinheiro, cedro e âmbar.",
        "price": 42,
        "stock": 15,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado",
        "top_notes": "Framboesa, Violeta, Maçã, Laranja",
        "heart_notes": "Rosa, Peónia, Íris, Jasmim",
        "base_notes": "Cipreste, Pinheiro, Cedro, Âmbar",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.78544.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "697cd386-7de6-4621-ac1c-78189d246d59",
        "name": "Hawas for Her",
        "brand": "Rasasi",
        "description": "Romã, íris e praliné num frasco de luxo.",
        "long_description": "Hawas for Her é frutado e sofisticado: romã, maçã e toranja na saída, um coração de íris, jasmim e citrinos, e uma base de praliné, patchouli e vetiver.",
        "price": 59,
        "stock": 14,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado",
        "top_notes": "Romã, Maçã, Toranja",
        "heart_notes": "Íris, Jasmim, Citrinos",
        "base_notes": "Praliné, Patchouli, Vetiver",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.67146.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "671bf34c-6fff-43fc-bf0c-bf2100d1f03c",
        "name": "Delilah",
        "brand": "Maison Alhambra",
        "description": "Ruibarbo, líchia e rosa num perfil delicado.",
        "long_description": "Delilah é romântico e luminoso: ruibarbo, líchia e bergamota na abertura, um bouquet de rosa, peónia e lírio, e uma base de almíscar, cashmeran e baunilha.",
        "price": 29,
        "stock": 24,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Floral Frutado",
        "top_notes": "Ruibarbo, Líchia, Bergamota",
        "heart_notes": "Rosa, Peónia, Lírio",
        "base_notes": "Almíscar, Cashmeran, Baunilha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.90273.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "25ac085e-c562-4340-a96e-27ccb3d9ff47",
        "name": "L'Aventure Femme",
        "brand": "Al Haramain",
        "description": "Ananás, groselha preta e frésia com fundo de baunilha.",
        "long_description": "L'Aventure Femme é frutado e confiante: ananás, groselha preta, bergamota e frutos silvestres, um coração de cedro, frésia e rosa, e uma base de almíscar, sândalo, âmbar e baunilha.",
        "price": 38,
        "stock": 16,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "100ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Chipre Frutado",
        "top_notes": "Ananás, Groselha Preta, Bergamota, Frutos Silvestres",
        "heart_notes": "Cedro, Frésia, Rosa",
        "base_notes": "Almíscar, Sândalo, Âmbar, Baunilha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.51820.jpg",
        "rating": 4.5,
        "review_count": 0
    },
    {
        "id": "0081a20e-ee01-4e0e-adb9-b24a6cb5efaa",
        "name": "Evoke for Her",
        "brand": "Ajmal",
        "description": "Pimenta rosa, rosa e íris com fundo de patchouli.",
        "long_description": "Evoke for Her é um chipre floral moderno: pimenta rosa e bergamota na saída, um coração de rosa, raiz de íris e jasmim, e uma base de patchouli, musgo de carvalho e baunilha.",
        "price": 52,
        "stock": 10,
        "category": "perfumes",
        "subcategory": "Feminino",
        "gender": "Feminino",
        "volume": "75ml",
        "concentration": "Eau de Parfum",
        "fragrance_family": "Chipre Floral",
        "top_notes": "Pimenta Rosa, Bergamota",
        "heart_notes": "Rosa, Raiz de Íris, Jasmim",
        "base_notes": "Patchouli, Musgo de Carvalho, Baunilha",
        "origin_country": "Emirados Árabes Unidos",
        "show_on_home": false,
        "image_url": "https://fimgs.net/mdimg/perfume/375x500.32526.jpg",
        "rating": 4.5,
        "review_count": 0
    }
];
